import { Configuration } from './tomb-finance/config';
import { BankInfo } from './tomb-finance';

const configurations: { [env: string]: Configuration } = {
  production: {
    chainId: 42161,
    networkName: 'Fantom Opera Mainnet',
    etherscanUrl: 'https://arbiscan.com',
    defaultProvider: 'https://arb1.arbitrum.io/rpc',
    deployments: require('./tomb-finance/deployments/deployments.mainnet.json'),
    externalTokens: {
      WETH: ['0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', 18],
      USDC: ['0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8', 6],
      wFTM: ['0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', 18],
      'RRBOMB-WETH LP': ['0x1dE807C94D1637be2267A937fd5aB07a16c30579', 18],
      'RRBSHARE-WETH LP': ['0x082a88164A4c06076a844AB120716EB3925908F2', 18],
      ARBSHARES: ['0x9664E90eb98Be3671E940e42aFdEd1B56c364185', 18],
      'USDC-ETH-LP': ['0x84652bb2539513BAf36e225c930Fdd8eaa63CE27', 18],
      'RRBOMB-ETH-LP': ['0x1dE807C94D1637be2267A937fd5aB07a16c30579', 18],
      'RRBSHARE-ETH-LP': ['0x082a88164A4c06076a844AB120716EB3925908F2', 18],
    },
    baseLaunchDate: new Date('2021-06-02 13:00:00Z'),
    bondLaunchesAt: new Date('2020-12-03T15:00:00Z'),
    masonryLaunchesAt: new Date('2020-12-11T00:00:00Z'),
    refreshInterval: 10000,
  },
};

export const bankDefinitions: { [contractName: string]: BankInfo } = {
  /*
  Explanation:
  name: description of the card
  poolId: the poolId assigned in the contract
  sectionInUI: way to distinguish in which of the 3 pool groups it should be listed
        - 0 = Single asset stake pools
        - 1 = LP asset staking rewarding TOMB
        - 2 = LP asset staking rewarding TSHARE
  contract: the contract name which will be loaded from the deployment.environmnet.json
  depositTokenName : the name of the token to be deposited
  earnTokenName: the rewarded token
  finished: will disable the pool on the UI if set to true
  sort: the order of the pool
  */
  Tomb2sharesRewardPool: {
    name: 'Earn RRBOMB by staking 2SHARES',
    poolId: 0,
    sectionInUI: 0,
    contract: 'Tomb2ShareRewardPool',
    depositTokenName: '2SHARES',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '7500x',
    site: 'https://2omb.finance',
    buyLink: 'https://spookyswap.finance/swap?outputCurrency=0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    sort: 0,
    closedForStaking: true,
  },
  Tomb2sharesWftmLPRewardPool: {
    name: 'Earn RRBOMB by staking 2SHARES-WETH LP',
    poolId: 1,
    sectionInUI: 0,
    contract: 'Tomb2SharesWftmLPRewardPool',
    depositTokenName: '2SHARES-WETH LP',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '6000x',
    site: 'https://2omb.finance',
    buyLink: 'https://spookyswap.finance/add/ETH/0xc54A1684fD1bef1f077a336E6be4Bd9a3096a6Ca',
    sort: 1,
    closedForStaking: true,
  },
  // Tomb2shares2ombLPRewardPool: {
  //   name: 'Earn RRBOMB by staking 2OMB-2SHARES LP',
  //   poolId: 2,
  //   sectionInUI: 0,
  //   contract: 'Tomb2Shares2ombLPRewardPool',
  //   depositTokenName: '2OMB-2SHARES LP',
  //   earnTokenName: 'RRBOMB',
  //   finished: false,
  //   multiplier: '6000',
  //   site: "https://2omb.finance",
  //   buyLink: 'https://spookyswap.finance/add/0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae/0xc54A1684fD1bef1f077a336E6be4Bd9a3096a6Ca',
  //   sort: 2,
  //   closedForStaking: false,
  // },
  Tomb2ombWftmLPRewardPool: {
    name: 'Earn RRBOMB by staking 2OMB-WETH LP',
    poolId: 2,
    sectionInUI: 0,
    contract: 'Tomb2ombWftmLPRewardPool',
    depositTokenName: '2OMB-WETH LP',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '6000x',
    site: 'https://2omb.finance',
    buyLink: 'https://spookyswap.finance/add/ETH/0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    sort: 3,
    closedForStaking: true,
  },
  Tomb2ombRewardPool: {
    name: 'Earn RRBOMB by staking 2OMB',
    poolId: 3,
    sectionInUI: 0,
    contract: 'Tomb2ombRewardPool',
    depositTokenName: '2OMB',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '5000x',
    site: 'https://2omb.finance',
    buyLink: 'https://spookyswap.finance/swap?outputCurrency=0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    sort: 4,
    closedForStaking: true,
  },
  TombBelugaRewardPool: {
    name: 'Earn RRBOMB by staking BELUGA',
    poolId: 4,
    sectionInUI: 0,
    contract: 'TombBelugaRewardPool',
    depositTokenName: 'BELUGA',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '500x',
    site: 'https://beluga.fi',
    buyLink:
      'https://beets.fi/#/trade/0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83/0x4A13a2cf881f5378DEF61E430139Ed26d843Df9A',
    sort: 5,
    closedForStaking: true,
  },
  TombBifiRewardPool: {
    name: 'Earn RRBOMB by staking BIFI',
    poolId: 5,
    sectionInUI: 0,
    contract: 'TombBifiGenesisRewardPool',
    depositTokenName: 'BIFI',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '500x',
    site: 'https://app.beefy.finance/#/fantom',
    buyLink:
      'https://beets.fi/#/trade/0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83/0xd6070ae98b8069de6B494332d1A1a81B6179D960',
    sort: 6,
    closedForStaking: true,
  },
  TombWrappedFtmRewardPool: {
    name: 'Earn RRBOMB by staking WETH',
    poolId: 6,
    sectionInUI: 0,
    contract: 'TombWrappedFtmRewardPool',
    depositTokenName: 'wFTM',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '500x',
    site: 'https://fantom.foundation',
    buyLink: 'https://ecoswap.exchange',
    sort: 7,
    closedForStaking: true,
  },
  TombMimRewardPool: {
    name: 'Earn RRBOMB by staking MIM',
    poolId: 7,
    sectionInUI: 0,
    contract: 'TombMimGenesisRewardPool',
    depositTokenName: 'MIM',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '500x',
    site: 'https://abracadabra.money/',
    buyLink: 'https://ftm.curve.fi/factory/7',
    sort: 8,
    closedForStaking: true,
  },
  TombBloomRewardPool: {
    name: 'Earn RRBOMB by staking BLOOM',
    poolId: 8,
    sectionInUI: 0,
    contract: 'TombBloomGenesisRewardPool',
    depositTokenName: 'BLOOM',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '500x (0.04% Deposit Fee)',
    site: 'https://bloom.thetulipdao.com/',
    buyLink: 'https://swap.spiritswap.finance/#/exchange/swap/ETH/0x9B2e37cDC711CfcAC1E1482B5741c74dd3924199',
    sort: 9,
    closedForStaking: true,
  },
  TombFtmLPTombRewardPool: {
    name: 'Earn TOMB by TOMB-ETH LP',
    poolId: 0,
    sectionInUI: 1,
    contract: 'TombFtmLpTombRewardPool',
    depositTokenName: 'RRBOMB-ETH-LP',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 7,
    closedForStaking: true,
  },
  TombFtmLPTombRewardPoolOld: {
    name: 'Earn TOMB by TOMB-ETH LP',
    poolId: 0,
    sectionInUI: 1,
    contract: 'TombFtmLpTombRewardPoolOld',
    depositTokenName: 'RRBOMB-ETH-LP',
    earnTokenName: 'TOMB',
    finished: true,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 9,
    closedForStaking: true,
  },
  TombFtmLPTShareRewardPool: {
    name: 'Earn ARBSHARES by 3 | ETH',
    poolId: 0,
    sectionInUI: 2,
    contract: 'TombFtmLPTShareRewardPool',
    depositTokenName: 'RRBOMB-WETH LP',
    earnTokenName: 'ARBSHARES',
    finished: false,
    multiplier: '35500x',
    buyLink: 'https://spookyswap.finance/add/ETH/0x14DEf7584A6c52f470Ca4F4b9671056b22f4FfDE',
    site: '/',
    sort: 8,
    closedForStaking: false,
  },
  TshareFtmLPTShareRewardPool: {
    name: 'Earn ARBSHARES by RRBSHARE-WETH LP',
    poolId: 1,
    sectionInUI: 2,
    contract: 'TshareFtmLPTShareRewardPool',
    depositTokenName: 'RRBSHARE-WETH LP',
    earnTokenName: 'ARBSHARES',
    finished: false,
    multiplier: '24000x',
    buyLink: 'https://spookyswap.finance/add/ETH/0x6437ADAC543583C4b31Bf0323A0870430F5CC2e7',
    site: '/',
    sort: 9,
    closedForStaking: false,
  },
  TwoshareFtmLPTShareRewardPool: {
    name: 'Earn ARBSHARES by 2SHARES-WETH LP',
    poolId: 2,
    sectionInUI: 2,
    contract: 'TwoshareFtmLPTShareRewardPool',
    depositTokenName: '2SHARES-WETH LP',
    earnTokenName: 'ARBSHARES',
    finished: false,
    multiplier: '15000x',
    buyLink: 'https://spookyswap.finance/add/ETH/0xc54A1684fD1bef1f077a336E6be4Bd9a3096a6Ca',
    site: 'https://2omb.finance',
    sort: 10,
    closedForStaking: false,
  },
  TwoombFtmLPTShareRewardPool: {
    name: 'Earn ARBSHARES by 2OMB-WETH LP',
    poolId: 3,
    sectionInUI: 2,
    contract: 'TwoombFtmLPTShareRewardPool',
    depositTokenName: '2OMB-WETH LP',
    earnTokenName: 'ARBSHARES',
    finished: false,
    multiplier: '15000x',
    buyLink: 'https://spookyswap.finance/add/ETH/0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    site: 'https://2omb.finance',
    sort: 11,
    closedForStaking: false,
  },
  // TwoombTwosharesLPTShareRewardPool: {
  //   name: 'Earn ARBSHARES by 2OMB-2SHARES LP',
  //   poolId: 4,
  //   sectionInUI: 2,
  //   contract: 'TwoombTwosharesLPTShareRewardPool',
  //   depositTokenName: '2OMB-2SHARESLP',
  //   earnTokenName: 'TSHARE',
  //   finished: false,
  //   multiplier: '0',
  //   buyLink: '',
  //   site: '',
  //   sort: 12,
  //   closedForStaking: false,
  // },
  Tomb2SHARESRebates: {
    name: 'Bond 2SHARES, earn RRBOMB',
    poolId: 0,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: '2SHARES',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '10000x',
    buyLink: '',
    site: '',
    sort: 5,
    closedForStaking: false,
  },
  WFTMRebates: {
    name: 'Bond WETH, earn RRBOMB',
    poolId: 1,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'WETH',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '15000x',
    buyLink: '',
    site: '',
    sort: 6,
    closedForStaking: false,
  },
  // USDCRebates: {
  //    name: 'Bond USDC, earn RRBOMB',
  //    poolId: 1,
  //    sectionInUI: 3,
  //    contract: 'TombFtmRewardPool',
  //    depositTokenName: 'USDC',
  //    earnTokenName: 'RRBOMB',
  //    finished: false,
  //    multiplier: '15000x',
  //    buyLink: '',
  //    site: '',
  //    sort: 6,
  //    closedForStaking: false,
  // },
  Tomb2SHARESFTMRebates: {
    name: 'Bond 2SHARES-WETH LP, earn RRBOMB',
    poolId: 2,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: '2SHARES-WETH LP',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '12000x',
    buyLink: '',
    site: '',
    sort: 4,
    closedForStaking: false,
  },
  // Tomb3OMBFTMRebates: {
  //   name: 'Bond RRBOMB-WETH LP, earn RRBOMB',
  //   poolId: 3,
  //   sectionInUI: 3,
  //   contract: 'TombFtmRewardPool',
  //   depositTokenName: 'RRBOMB-WETH LP',
  //   earnTokenName: 'RRBOMB',
  //   finished: false,
  //   multiplier: '6000x',
  //   buyLink: '',
  //   site: '',
  //   sort: 1,
  //   closedForStaking: false,
  // },
  Tomb3SHARESRebates: {
    name: 'Bond ARBSHARES, earn RRBOMB',
    poolId: 4,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'ARBSHARES',
    earnTokenName: 'RRBOMB',
    finished: false,
    multiplier: '5000x',
    buyLink: '',
    site: '',
    sort: 3,
    closedForStaking: false,
  },
  //Tomb3SHARESFTMRebates: {
  // name: 'Bond RRBSHARE-WETH LP, earn RRBOMB',
  // poolId: 5,
  // sectionInUI: 3,
  //  contract: 'TombFtmRewardPool',
  //  depositTokenName: 'RRBSHARE-WETH LP',
  //  earnTokenName: 'RRBOMB',
  //  finished: false,
  //  multiplier: '6000x',
  //  buyLink: '',
  //   site: '',
  //   sort: 2,
  //   closedForStaking: false,
  // },
};

export const ETHER_UNITS = {
  noether: '0',
  wei: '1',
  kwei: '1000',
  Kwei: '1000',
  babbage: '1000',
  femtoether: '1000',
  mwei: '1000000',
  Mwei: '1000000',
  lovelace: '1000000',
  picoether: '1000000',
  gwei: '1000000000',
  Gwei: '1000000000',
  shannon: '1000000000',
  nanoether: '1000000000',
  nano: '1000000000',
  szabo: '1000000000000',
  microether: '1000000000000',
  micro: '1000000000000',
  finney: '1000000000000000',
  milliether: '1000000000000000',
  milli: '1000000000000000',
  ether: '1000000000000000000',
  kether: '1000000000000000000000',
  grand: '1000000000000000000000',
  mether: '1000000000000000000000000',
  gether: '1000000000000000000000000000',
  tether: '1000000000000000000000000000000',
};

export default configurations['production'];
